({
  "saveDialogRecommend": "Salvati modificarile anterioare inainte de a continua? (Altfel, modificarile Dvs. se vor pierde)",
  "saveDialogSaveLabel": "Salvati",
  "saveDialogDiscardLabel": "Ignora modificarile",
  "saveDialogCancelLabel": "Anulare",
  "dialogTitle": "Editare metadata  pentru",
  "mandatoryLabel": "Imputernicit",
  "recommendedLabel": "Recomandat",
  "colorLabel": "Culoarea etichetelor",
  "shameMessageLabel": "Forma este in constructie, va rugam sa reveniti.",
  "readyForValidationLabel": "Gata pentru validare",
  "optionalLabel": "Optional",
  "dialogCancelLabel": "Anulare",
  "dialogDoneLabel": "Finalizat",
  "dialogDoneBusyLabel": "Salvare",
  "mandatoryElementsMissing": "Elementele obligatorii lipsesc!",
  "changeToLinkReference": "Nu aveti dreptul de a schimba aceasta intrare, deci acesta poate contine date localizate in metadata, in plus fata de datele de referinta",
  "failedSavingUnsufficientMDRights": "Nu aveti dreptul de a salva metadata.",
  "modifiedPreviouslyOnServer": "EROARE: Resursa a fost schimbata pe server, schimbarile Dvs. nu pot fi salvate."
})
