({
  "aboutLink": "Információ",
  "noAbout": "No text provided for this application",
  "helpLink": "Segítség",
  "noHelp": "No help text provided for this application",
  "loginLink": "Bejelentkezés",
  "logoutLink": "Kijelentkezés",
  "greeting": "Üdvözöljük",
  "guestUser": "Vendég",
  "homeLink": "Kezdõoldal",
  "contextLabel": "Portfólió",
  "searchLabel": "Keresés",
  "searchAllLabel": "Keresés minden portfólióban",
  "searchAllChecked": false,
  "searchFolderLabel": "Csak ebben a mappában",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Keresés a nem véleményezett dokumentumok között",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Felhasználó keresése",
  "searchUserChecked": false,
  "searchFieldMessage": "Gépelje ide a keresõszavakat",
  "changeUserDialogTitle": "Felhasználóváltás",
  "notLoggedInNoHomeMessage": "Mivel nem jelentkezett be, ezért nem tudjuk az alapértelmezett portfólióhoz továbbítani. ",
  "searchTermFiveCharsMessage": "Kérjük írja ide a legalább három karakter hosszú keresõszót. ",
  "searchFailedMessage": "Keresés sikertelen",
  "languageLabel": "Nyelv"
})