({
  "aboutLink": "Über",
  "noAbout": "Für diese Anwendung ist kein Text verfügbar",
  "helpLink": "Hilfe",
  "noHelp": "Für diese Anwendung ist kein Hilfetext verfügbar",
  "loginLink": "Anmelden",
  "logoutLink": "Abmelden",
  "greeting": "Willkommen",
  "guestUser": "Gast",
  "homeLink": "Nach Hause",
  "contextLabel": "Portfolio",
  "searchLabel": "Suchen",
  "searchAllLabel": "In allen Portfolios suchen",
  "searchAllChecked": false,
  "searchFolderLabel": "Nur dieses Verzeichnis",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Nur nach unveränderten Ressourcen suchen",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Nach Anwender suchen",
  "searchUserChecked": false,
  "searchFieldMessage": "Suchbegriff",
  "changeUserDialogTitle": "Benutzer wechseln",
  "notLoggedInNoHomeMessage": "Um zu ihrem Portfolio zu gelangen müssen sie angemeldet sein",
  "searchTermFiveCharsMessage": "Es sind mindestens 3 Buchstaben notwendig",
  "searchFailedMessage": "Während der Suche ist ein Fehler aufgetreten",
  "languageLabel": "Sprache"
})
