({
  "saveDialogRecommend": "Enregistrer les modifications avant de continuer ? (Sinon, les modifications seront perdues)",
  "saveDialogSaveLabel": "Sauvegarder",
  "saveDialogDiscardLabel": "Annuler les modifications",
  "saveDialogCancelLabel": "Annuler",
  "dialogTitle": "Editer les métadonnées pour",
  "mandatoryLabel": "Obligatoire",
  "recommendedLabel": "Recommendé",
  "colorLabel": "Color labels",
  "shameMessageLabel": "Le formulaire est en construction, attendez SVP",
  "readyForValidationLabel": "Prêt pour validation",
  "optionalLabel": "Optionnel",
  "dialogCancelLabel": "Annuler",
  "dialogDoneLabel": "Fait",
  "dialogDoneBusyLabel": "En cours de sauvegarde",
  "mandatoryElementsMissing": "Eléments obligatoires manquant !",
  "changeToLinkReference": "Vous n'avez pas les droits suffisants pour modifier cette entrée de manière à ce qu'il contienne des métadonnées locales en plus des métadonnées de référence.",
  "failedSavingUnsufficientMDRights": "Vous n'avez pas les droits suffisants pour sauvegarder cette métadonnée",
  "modifiedPreviouslyOnServer": "ERREUR : La ressource a été modifiée sur le serveur, vos modifications n'ont PAS été sauvegardées."
})