({
  "details": "Détails",
  "comment": "Commentaire",
  "edit": "Edition",
  "admin": "Administrer",
  "remove": "Détruire",
  "empty": "Vider",
  "copy": "Copier",
  "cut": "Couper",
  "paste": "Coller",
  "pasteInto": "Coller dans",
  "add": "Ajouter",
  "modified": "Modifié",
  "items": "Articles",
  "addedToContactsMessage": "Cette personne a été ajoutée à vos contacts",
  "sortLabel": "Trier par",
  "sortByNone": "Ordre de la liste",
  "sortByTitle": "Titre",
  "sortByTitleReverse": "Title inversé",
  "sortByModified": "Modification",
  "sortByModifiedReverse": "Modification inversée"
})