({
  "aboutLink": "A propos...",
  "helpLink": "Aide",
  "loginLink": "Connexion",
  "logoutLink": "Déconnexion",
  "greeting": "Bienvenue",
  "guestUser": "Invité",
  "homeLink": "Accueil",
  "contextLabel": "Portfolio",
  "searchLabel": "Recherche",
  "searchAllLabel": "Tous les portfolios",
  "searchAllChecked": false,
  "searchToBeAnnotatedLabel": "Seulement les ressources collectés et non éditées",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Recherche d'un utilisateur",
  "searchUserChecked": false,
  "searchFieldMessage": "Termes de recherche",
  "changeUserDialogTitle": "Changer d'utilisateur",
  "notLoggedInNoHomeMessage": "Comme vous n'êtes pas identifié(e), vous ne pouvez pas basculer vers votre portfolio",
  "searchTermFiveCharsMessage": "Entrez une recherche d'au moins 3 mots, SVP.",
  "searchFailedMessage": "La recherche a échoué",
  "languageLabel": "Langue"
})