({
  "aboutLink": "Despre",
  "noAbout": "Nu exista furnizat text pentru aceasta aplicatie",
  "helpLink": "Ajutor",
  "noHelp": "Nu este furnizat text ca ajutor pentru aceasta aplicatie",
  "loginLink": "Logare",
  "logoutLink": "Iesire",
  "greeting": "Bine ati venit!",
  "guestUser": "Vizitator",
  "homeLink": "Home",
  "contextLabel": "Portofoliu",
  "searchLabel": "Cautare",
  "searchAllLabel": "Cautare in toate portofoliile",
  "searchAllChecked": false,
  "searchFolderLabel": "Doar acest fisier",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Cautare numai pentru resursele neediate",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Cautare utilizator",
  "searchUserChecked": false,
  "searchFieldMessage": "Cautare dupa tipul termenilor",
  "changeUserDialogTitle": "Schimbare utilizator",
  "notLoggedInNoHomeMessage": "Din moment ce nu sunteti logat, nu exista nici un portofoliu de start pentru a va comuta la resursa",
  "searchTermFiveCharsMessage": "Va rugam introduceti cautarea termenului cu cel putin 3 caractere.",
  "searchFailedMessage": "cautarea a esuat.",
  "languageLabel": "Limba"
})
