({
  "saveDialogRecommend": "Αποθήκευση αλλαγών πριν τη συνέχεια; (Αλλιώς οι αλλαγές που κάνατε θα χαθούν)",
  "saveDialogSaveLabel": "Αποθήκευση",
  "saveDialogDiscardLabel": "Απόρριψη αλλαγών",
  "saveDialogCancelLabel": "Ακύρωση",
  "dialogTitle": "Επεξεργασία μεταδεδομένων για ",
  "mandatoryLabel": "Υποχρεωτικά",
  "recommendedLabel": "Προτεινόμενα",
  "colorLabel": "Έγχρωμες ετικέτες",
  "shameMessageLabel": "Η φόρμα δημιουργείται, παρακαλώ περιμένετε.",
  "readyForValidationLabel": "Έτοιμο για έλεγχο",
  "optionalLabel": "Προαιρετικά",
  "dialogCancelLabel": "Ακύρωση",
  "dialogDoneLabel": "Τέλος",
  "dialogDoneBusyLabel": "Αποθήκευση",
  "mandatoryElementsMissing": "Λείπουν υποχρεωτικά πεδία!",
  "changeToLinkReference": "Δεν έχετε τα απαιτούμενα δικαιώματα για να αλλάξετε την παρούσα καταχώρηση έτσι ώστε να περιέχει τοπικά μεταδεδομένα επιπρόσθετα από μεταδεδομένα αναφοράς..",
  "failedSavingUnsufficientMDRights": "Δεν έχετε τα απαιτούμενα δικαιώματα για να αποθηκεύσετε τα μεταδεδομένα.",
  "modifiedPreviouslyOnServer": "ΣΦΑΛΜΑ: Ο πόρος έχει αλλάξει στον διακομιστή, οι αλλαγές σας ΔΕΝ έχουν αποθηκευθεί."
})