({
  "aboutLink": "Om",
  "noAbout": "Ingen text finns för den här applikationen",
  "helpLink": "Hjälp",
  "noHelp": "Ingen hjälptext finns för den här applikationen",
  "loginLink": "Logga in",
  "logoutLink": "Logga ut",
  "greeting": "Välkommen",
  "guestUser": "Gäst",
  "homeLink": "Hem",
  "settings": "Inställningar",
  "contextLabel": "Portfölj",
  "searchLabel": "Sök",
  "searchAllLabel": "Sök i alla portföljer",
  "searchAllChecked": false,
  "searchFolderLabel": "Only this folder",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Sök endast ej beskrivna resurser",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Sök användare",
  "searchUserChecked": false,
  "searchFieldMessage": "Skriv sökord här",
  "changeUserDialogTitle": "Användarinställningar",
  "notLoggedInNoHomeMessage": "Eftersom du inte är inloggad så har du ingen hemportfölj.",
  "searchTermFiveCharsMessage": "Var god ange en sökterm med minst tre bokstäver.",
  "searchFailedMessage": "Sökning misslyckades.",
  "languageLabel": "Språk"
})