({
  "saveDialogRecommend": "¿Desea guardar los cambios? (si no lo hace perderá los últimos cambios)",
  "saveDialogSaveLabel": "Guardar",
  "saveDialogDiscardLabel": "No guardar los cambios",
  "saveDialogCancelLabel": "Cancelar",
  "dialogTitle": "Editar metadatos para",
  "mandatoryLabel": "Obligatorio",
  "recommendedLabel": "Recomendado",
  "colorLabel": "Etiquetas de color",
  "shameMessageLabel": "Formulario en construcción, espere por favor",
  "readyForValidationLabel": "Listo para validar",
  "optionalLabel": "Opcional",
  "dialogCancelLabel": "Cancelar",
  "dialogDoneLabel": "Hecho",
  "dialogDoneBusyLabel": "Guardando",
  "mandatoryElementsMissing": "Faltan elementos obligatorios!",
  "changeToLinkReference": "No tiene suficientes permisos para modificar esta entrada ya que contiene metadatos locales además de los metadatos referenciados. ",
  "failedSavingUnsufficientMDRights": "No tiene suficientes permisos para guardar los metadatos. ",
  "modifiedPreviouslyOnServer": "ERROR: El recurso ha cambiado en el servidor, sus cambions NO han sido guardados."
})