({
  "details": "Detalles",
  "comment": "Commentario",
  "edit": "Editar",
  "admin": "Administrar",
  "remove": "Borrar",
  "empty": "Vacío",
  "copy": "Copiar",
  "cut": "Cortar",
  "paste": "Pegar",
  "pasteInto": "Pegar en",
  "add": "Añadir",
  "modified": "Modificado",
  "items": "Items",
  "addedToContactsMessage": "Esta persona ha sido añadida a sus contactos.",
  "sortLabel": "Ordenado por",
  "sortByNone": "Orden de lista",
  "sortByTitle": "Título",
  "sortByTitleReverse": "Título inverso",
  "sortByModified": "Modificado",
  "sortByModifiedReverse": "Modificado inverso"
})