({
  "aboutLink": "Hakkýnda",
  "helpLink": "Yardým",
  "loginLink": "Sisteme baðlan",
  "logoutLink": "Sistemden çýk",
  "greeting": "Hoþ geldiniz",
  "guestUser": "Konuk",
  "homeLink": "Anasayfa",
  "contextLabel": "Portfolyo",
  "searchLabel": "Ara",
  "searchAllLabel": "Tüm portfolyolar",
  "searchAllChecked": false,
  "searchToBeAnnotatedLabel": "Yalnýz henüz düzenlenmemiþ olan hasat edilmiþ kaynaklar",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Kullanýcý ara",
  "searchUserChecked": false,
  "searchFieldMessage": "Aranacak sözcükleri buraya gir",
  "changeUserDialogTitle": "Kullanýcý deðiþtir",
  "notLoggedInNoHomeMessage": "Sisteme giriþ yapmadýðýnýz için gidilecek ana portfolyonuz yok.",
  "searchTermFiveCharsMessage": "Lütfen en az 3 karakterden oluþan bir aranacak sözcük giriniz.",
  "searchFailedMessage": "Arama iþlemi baþarýsýz.",
  "languageLabel": "Dil"
})