({
  "saveDialogRecommend": "Salvare le modifiche prima di continuare? (Altrimenti le modifiche andranno perse)",
  "saveDialogSaveLabel": "Salva",
  "saveDialogDiscardLabel": "Abbandona le modifiche",
  "saveDialogCancelLabel": "Cancella",
  "dialogTitle": "Modifica i metadati per",
  "mandatoryLabel": "Obbligatorio",
  "recommendedLabel": "Consigliato",
  "colorLabel": "Colore etichette",
  "shameMessageLabel": "Si sta creando il modulo, attendere prego.",
  "readyForValidationLabel": "Pronto per la convalida",
  "optionalLabel": "Facoltativo",
  "dialogCancelLabel": "Cancella",
  "dialogDoneLabel": "Fatto",
  "dialogDoneBusyLabel": "Salvataggio in corso",
  "mandatoryElementsMissing": "Elementi obbligatori mancanti!",
  "changeToLinkReference": "Non si dispone di diritti sufficienti per modificare questa voce in modo che contenga metadati locali oltre ai metadati referenziati.",
  "failedSavingUnsufficientMDRights": "Non si dispone di diritti sufficienti per salvare i metadati.",
  "modifiedPreviouslyOnServer": "ERRORE: La risorsa stata modificata sul server, le tue modifiche NON sono state salvate."
})