({
  "aboutLink": "Info",
  "noAbout": "Nessun testo fornito per questa applicazione",
  "helpLink": "Aiuto",
  "noHelp": "Nessun testo d'aiuto fornito per questa applicazione",
  "loginLink": "Entra",
  "logoutLink": "Esci",
  "greeting": "Benvenuto",
  "guestUser": "Ospite",
  "homeLink": "Home",
  "contextLabel": "Portfolio",
  "searchLabel": "Ricerca",
  "searchAllLabel": "Tutti i portfolio",
  "searchAllChecked": "false",
  "searchFolderLabel": "Solo questa cartella",
  "searchFolderChecked": "Le cartelle selezionate",
  "searchToBeAnnotatedLabel": "Solo le risorse recuperate e non annotate",
  "searchToBeAnnotatedChecked": "false",
  "searchUserLabel": "Cerca utente",
  "searchUserChecked": "false",
  "searchFieldMessage": "Scrivere i termini per la ricerca qui",
  "changeUserDialogTitle": "Cambia utente",
  "notLoggedInNoHomeMessage": "Non siete registrati quindi non potete cambiare portfolio",
  "searchTermFiveCharsMessage": "Per la ricerca si prega di inserire un termine di almeno 3 caratteri",
  "searchFailedMessage": "Ricerca non riuscita",
  "languageLabel": "Lingua"
})