({
  "saveDialogRecommend": "إحفظ التغييرات قبل المتابعة؟ (غير ذلك سيتم فقدان التغييرات)",
  "saveDialogSaveLabel": "إحفظ",
  "saveDialogDiscardLabel": "تجاهل التغييرات",
  "saveDialogCancelLabel": "إلغاء",
  "dialogTitle": "حرر المعلومات المتعلقة لـ",
  "mandatoryLabel": "إالزامي",
  "recommendedLabel": "موصى به",
  "colorLabel": "لون الطوابع",
  "shameMessageLabel": "النموذج قيد الإنشاء، يرجى الإنتظار",
  "readyForValidationLabel": "جاهز لتفعيل",
  "optionalLabel": "إختياري",
  "dialogCancelLabel": "إالغاء",
  "dialogDoneLabel": "تم",
  "dialogDoneBusyLabel": "قيد الحفظ",
  "mandatoryElementsMissing": "عناصر إلزامية ناقصة!",
  "changeToLinkReference": "ليس لديك الصلاحيات الكافية لتغيير هذا الإدخال حيث أنه قد تحتوي على معلومات متعلقة محلية، بالإضافة إلى المعلومات المتعلقة المشار إليها",
  "failedSavingUnsufficientMDRights": "ليس لديك الصلاحيات الكافية لحفظ المعلومات المتعلقة",
  "modifiedPreviouslyOnServer": "خطأ : لقد تم تغيير المورد على الخادم، لم يتم حفظ التغييرات"
})