({
  "aboutLink": "حول",
  "noAbout": "لم يزود أي نص لهذا التطبيق",
  "helpLink": "مساعدة",
  "noHelp": "لم يزود نص مساعدة لهذا التطبيق",
  "loginLink": "تسجيل الدخول",
  "logoutLink": "تسجيل الخروج",
  "greeting": "أهلا بك",
  "guestUser": "ضيف",
  "homeLink": "الرئيسية",
  "contextLabel": "الملف الشخصي",
  "searchLabel": "بحث",
  "searchAllLabel": "كل الملفات الشخصية",
  "searchAllChecked": خاطئ,
  "searchFolderLabel": "فقط هذا المجلد",
  "searchFolderChecked": خاطئ,
  "searchToBeAnnotatedLabel": "فقط الموارد المحصلة الغير منقحة",
  "searchToBeAnnotatedChecked": خاطئ,
  "searchUserLabel": "إبحث عن المستخدم",
  "searchUserChecked": خاطئ,
  "searchFieldMessage": "إطبع مصطلحات البحث هنا",
  "changeUserDialogTitle": "غير المستخدم",
  "notLoggedInNoHomeMessage": "بما أنك غير مسجل دخولك فلا يوجد ملف شخصي رئيسي لتحويل إليه",
  "searchTermFiveCharsMessage": "رجاءا أدخل مصطلح البحث مع 3 حروف على الأقل",
  "searchFailedMessage": "فشل البحث",
  "languageLabel": "اللغة"
})