({
  "saveDialogRecommend": "Lagre endringene før du fortsetter? (Ellers vil de gå tapt)",
  "saveDialogSaveLabel": "Lagre",
  "saveDialogDiscardLabel": "Ikke lagre",
  "saveDialogCancelLabel": "Avbryt",
  "dialogTitle": "Endre metadata for",
  "mandatoryLabel": "Obligatorisk",
  "recommendedLabel": "Anbefalt",
  "colorLabel": "Farg feltnavnene",
  "shameMessageLabel": "Formularet lages, vennligst vent.",
  "readyForValidationLabel": "Klar for validering",
  "optionalLabel": "Valgfritt",
  "dialogCancelLabel": "Avbryt",
  "dialogDoneLabel": "Ferdig",
  "dialogDoneBusyLabel": "Lagrer",
  "mandatoryElementsMissing": "Obligatoriske felt mangler!",
  "changeToLinkReference": "Du har ikke tilstrekkelige rettigheter til å endre denne ressursen slik at den inneholder lokal metadata i tillegg til opprinnelig metadata.",
  "failedSavingUnsufficientMDRights": "Du har ikke tilstrekkelige rettigheter til å lagre metadata.",
  "modifiedPreviouslyOnServer": "FEIL: Ressursen er blitt endret på serveren, dine endringer er IKKE blitt lagret."
})