({
  "aboutLink": "Om",
  "noAbout": "Det finnes ingen informasjon om denne ressursen",
  "helpLink": "Hjelp",
  "noHelp": "Det finnes ingen hjelpeinformasjon om denne ressursen",
  "loginLink": "Logg inn",
  "logoutLink": "Logg ut",
  "greeting": "Velkommen",
  "guestUser": "Gjest",
  "homeLink": "Hjem",
  "contextLabel": "Portefølje",
  "searchLabel": "Søk",
  "searchAllLabel": "Søk i alle porteføljer",
  "searchAllChecked": false,
  "searchFolderLabel": "Søk kun i denne mappen",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Søk kun i ikke-beskrevne ressurser",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Søk etter bruker",
  "searchUserChecked": false,
  "searchFieldMessage": "Skriv søkeord her",
  "changeUserDialogTitle": "Bytt bruker",
  "notLoggedInNoHomeMessage": "Siden du ikke er innlogget, har du ingen portefølje å gå hjem til.",
  "searchTermFiveCharsMessage": "Vennligst skriv inn et søkeord med minst 3 tegn.",
  "searchFailedMessage": "Mislykket søk.",
  "languageLabel": "Språk"
})