({
  "saveDialogRecommend": "Menti a változásokat? (A nem mentett adatok elvesznek)",
  "saveDialogSaveLabel": "Mentés",
  "saveDialogDiscardLabel": "Változások visszavonása",
  "saveDialogCancelLabel": "Törlés",
  "dialogTitle": "Metaadat szerkesztése",
  "mandatoryLabel": "Kötelezõ",
  "recommendedLabel": "Ajánlott",
  "colorLabel": "címke",
  "shameMessageLabel": "Az ûrlap betöltés alatt, kérjük várjon. ",
  "readyForValidationLabel": "Validálásra kész",
  "optionalLabel": "Választható",
  "dialogCancelLabel": "Törlés",
  "dialogDoneLabel": "Kész",
  "dialogDoneBusyLabel": "Mentés",
  "mandatoryElementsMissing": "Kötelezõ elemek hiányoznak!",
  "changeToLinkReference": "Nincs jogosultsága a bejegyzés megváltoztatásához, mivel a hivatkozott metaadatok mellett helyi metaadatokat is tartalmazhat. ",
  "failedSavingUnsufficientMDRights": "Nincs jogosultsága a metaadatok elmentésére. ",
  "modifiedPreviouslyOnServer": "HIBA: A tananyag megváltozott a szerveren, a változtatások NEM sikerült menteni. "
})