({
  "aboutLink": "Več o tem",
  "helpLink": "Pomoč",
  "loginLink": "Vpis",
  "logoutLink": "Izpis",
  "greeting": "Dobrodošli",
  "guestUser": "Gost",
  "homeLink": "Domov",
  "contextLabel": "Portfelj",
  "searchLabel": "Išči",
  "searchAllLabel": "Vsi portfelji",
  "searchAllChecked": false,
  "searchFolderLabel": "Samo ta mapa",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Samo neurejeni viri",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Išči uporabnika",
  "searchUserChecked": false,
  "searchFieldMessage": "Tu vpišite iskalne izraze",
  "changeUserDialogTitle": "Spremeni uporabnika",
  "notLoggedInNoHomeMessage": "Ker niste vpisani, ni domačega portfelja na katerega bi preklopili.",
  "searchTermFiveCharsMessage": "Prosimo, vnesite izraz z najmanj 3 znaki.",
  "searchFailedMessage": "Iskanje ni uspelo.",
  "languageLabel": "Jezik"
})
