({
  "aboutLink": "Относно",
  "helpLink": "Помощ",
  "loginLink": "Име",
  "logoutLink": "Излизане",
  "greeting": "Добре дошли",
  "guestUser": "Гост",
  "homeLink": "Начало",
  "contextLabel": "Портфолио",
  "searchLabel": "Търси",
  "searchAllLabel": "Всички портфолиа",
  "searchAllChecked": false,
  "searchToBeAnnotatedLabel": "Само нередактирани ресурси",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Търси потребител",
  "searchUserChecked": false,
  "searchFieldMessage": "Впиши текст за търсене",
  "changeUserDialogTitle": "Промени потребителя",
  "notLoggedInNoHomeMessage": "Няма начално портфолио, тъй като не сте влезли",
  "searchTermFiveCharsMessage": "Моля, въведете текст за търсене с поне три символа",
  "searchFailedMessage": "Неуспешно търсене",
  "languageLabel": "Език"
})