({
  "aboutLink": "Σχετικά με",
  "noAbout": "Δεν παρέχεται κείμενο για αυτή την εφαρμογή",
  "helpLink": "Βοήθεια",
  "noHelp": "Δεν παρέχεται κείμενο βοηθείας για αυτή την εφαρμογή",
  "loginLink": "Σύνδεση",
  "logoutLink": "Αποσύνδεση",
  "greeting": "Καλωσήλθατε",
  "guestUser": "Μη εγγραγραμένος χρήστης",
  "homeLink": "Αρχική Σελίδα",
  "contextLabel": "Portfolio",
  "searchLabel": "Αναζήτηση",
  "searchAllLabel": "Αναζήτηση σε όλα τα portfolios",
  "searchAllChecked": false,
  "searchFolderLabel": "Only this folder",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Αναζήτηση μόνο για resources που δεν έχουν υποστεί επεξεργασία",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Search user",
  "searchUserChecked": false,
  "searchFieldMessage": "Πληκτρολογήστε τους όρους αναζήτησης εδώ",
  "changeUserDialogTitle": "Αλλαγή χρήστη",
  "notLoggedInNoHomeMessage": "Εφόσον δεν είστε συνδεδεμένος δεν υπάρχει αρχικό portfolio για να κατευθυνθείτε.",
  "searchTermFiveCharsMessage": "Παρακαλώ εισάγετε έναν όρο αναζήτησης με τουλάχιστον 3 χαρακτήρες.",
  "searchFailedMessage": "Αποτυχία αναζήτησης.",
  "languageLabel": "Γλώσσα"
})