({
  "aboutLink": "Acerca de",
  "noAbout": "No existe texto para esta aplicación",
  "helpLink": "Ayuda",
  "noHelp": "No existe texto de ayuda para esta aplicación",
  "loginLink": "Entrar",
  "logoutLink": "Salir",
  "greeting": "Bienvenido",
  "guestUser": "Invitado",
  "homeLink": "Inicio",
  "contextLabel": "Portafolio",
  "searchLabel": "Buscar",
  "searchAllLabel": "Buscar en todos los portafolios",
  "searchAllChecked": false,
  "searchFolderLabel": "Only this folder",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Buscar sólo recursos no editados",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Búsqueda de usuario",
  "searchUserChecked": false,
  "searchFieldMessage": "Introduzca los términos de búsqueda",
  "changeUserDialogTitle": "Cambiar usuario",
  "notLoggedInNoHomeMessage": "Al no estar logueado no hay portafolio al que cambiar. ",
  "searchTermFiveCharsMessage": "Por favor, introduzca un término de búsqueda de al menos 3 caracteres",
  "searchFailedMessage": "Búsqueda fallida.",
  "languageLabel": "Lenguaje"
})