({
  "aboutLink": "关于",
  "noAbout": "没有此应用程序的相关文档",
  "helpLink": "帮助",
  "noHelp": "没有此应用程序的帮助文档",
  "loginLink": "登录",
  "logoutLink": "注销",
  "greeting": "欢迎",
  "guestUser": "客人",
  "homeLink": "主集",
  "contextLabel": "作品集",
  "searchLabel": "查找",
  "searchAllLabel": "所有作品集",
  "searchAllChecked": false,
  "searchFolderLabel": "仅限此文件夹",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "仅限不可编辑的已收集的资源",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "查询用户",
  "searchUserChecked": false,
  "searchFieldMessage": "输入查询关键词",
  "changeUserDialogTitle": "变换用户",
  "notLoggedInNoHomeMessage": "因为您没有登录,所以这里没有您的作品主集可切换。",
  "searchTermFiveCharsMessage": "请输入一个查询关键词，最少包含３个字符。",
  "searchFailedMessage": "查询失败。",
  "languageLabel": "语言"
})
