({
  "aboutLink": "О",
  "noAbout": "Нет подходящего текста",
  "helpLink": "Помощь",
  "noHelp": "По данному запросу нет текста",
  "loginLink": "Вход",
  "logoutLink": "Выход",
  "greeting": "Добро пожаловать",
  "guestUser": "Гость",
  "homeLink": "Домой",
  "contextLabel": "Портфолио",
  "searchLabel": "Поиск",
  "searchAllLabel": "Все портфолио",
  "searchAllChecked": false,
  "searchFolderLabel": "Только эта папка",
  "searchFolderChecked": false,
  "searchToBeAnnotatedLabel": "Только неотредактированные ресурсы",
  "searchToBeAnnotatedChecked": false,
  "searchUserLabel": "Поиск пользователей",
  "searchUserChecked": false,
  "searchFieldMessage": "Вводите поисковые запросы здесь",
  "changeUserDialogTitle": "Смена пользователя",
  "notLoggedInNoHomeMessage": "Так как вы не вошли в систему, нет главного портфолио",
  "searchTermFiveCharsMessage": "Пожалуйста, в поисковый запрос введите, по крайней мере, 3 символа",
  "searchFailedMessage": "Не удалось выполнить поиск.",
  "languageLabel": "Язык"
})